#Service Account RBAC

#uugulamanın üzerinden API çağrısı yapabildiği  kimlik tanımlanır
#service account pod içerisinde çalışan uygulamanın Kubernetes'e karşı tesmil edilen kimliktir

apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-sa
  namespace: default


#kimliğin beilrlendiği yaml
